spring.application.name=spring-vulnerable-lab
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.profiles.default=dev
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

app.cors.allowed-origins=http://localhost:8081
security.jwt.secret=${JWT_SECRET:change-this-secret-in-production-with-at-least-32-characters}
security.jwt.expiration-seconds=3600
security.rate-limit.max-requests=120
security.rate-limit.window-seconds=60
